{% set version = "0.3.1" %}
{% set name = "demquery" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aaf59a283933dc43b2ac1f2097d85e4220bbdb46fa4b52e2879e111fcd687575

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5.0
    - pip
    - twine
  run:
    - python >=3.5.0
    - gdal >=2.4.0
    - numpy >=1.16
    - rasterio >=1.0
    - scipy

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/kylebarron/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around rasterio to query points on a Digital Elevation Model
  description: |
    Wrapper around rasterio to query points on a Digital Elevation Model
  dev_url: https://github.com/kylebarron/{{ name }}
  doc_url: https://pypi.python.org/pypi/{{ name }}
  doc_source_url: https://github.com/kylebarron/{{ name }}/blob/master/README.md

extra:
  recipe-maintainers:
    - kylebarron
